2016-07-08 15:55:43,380 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2016-07-08 15:55:43,490 - softwarecenter.db.database - ERROR - failed to add apt-xapian-index
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/database.py", line 194, in _get_new_xapiandb
    softwarecenter.paths.APT_XAPIAN_INDEX_DB_PATH)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 3667, in __init__
    _xapian.Database_swiginit(self,_xapian.new_Database(*args))
DatabaseOpeningError: Couldn't stat '/var/lib/apt-xapian-index/index' (No such file or directory)
2016-07-08 15:55:45,078 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2016-07-08 15:55:45,199 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2016-07-08 15:55:45,217 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2016-07-08 15:55:45,267 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-07-08 15:55:48,689 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2016-07-08 15:55:48,689 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')
2016-07-08 15:55:49,649 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
2016-07-08 15:55:49,651 - softwarecenter.db.database - ERROR - failed to add apt-xapian-index
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/database.py", line 194, in _get_new_xapiandb
    softwarecenter.paths.APT_XAPIAN_INDEX_DB_PATH)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 3667, in __init__
    _xapian.Database_swiginit(self,_xapian.new_Database(*args))
DatabaseOpeningError: Couldn't stat '/var/lib/apt-xapian-index/index' (No such file or directory)
2016-07-08 15:55:49,673 - softwarecenter.db.database - ERROR - failed to add apt-xapian-index
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/db/database.py", line 194, in _get_new_xapiandb
    softwarecenter.paths.APT_XAPIAN_INDEX_DB_PATH)
  File "/usr/lib/python2.7/dist-packages/xapian/__init__.py", line 3667, in __init__
    _xapian.Database_swiginit(self,_xapian.new_Database(*args))
DatabaseOpeningError: Couldn't stat '/var/lib/apt-xapian-index/index' (No such file or directory)
2016-07-08 15:58:49,403 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
